name: QuizGenerator
services:
  quizDb:
    container_name: quizDb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1qazXSW@
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - mssql_quiz:/var/lib/mssql/data/
  distributedcachequiz:
    container_name: distributedcachequiz
    restart: always
    ports:
      - "6379:6379"    
  qdrant:
    container_name: qdrantdb
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  ollama:
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama_volume:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]